require(compiler)
.clean <- function(x) {
        y <- gsub("’", "'", x)
        y <- iconv(y, "latin1", "ASCII", sub=" ")
        y <- gsub("D;|:o)|:c)|:D|:>|:-)", ". ", y)
        y <- gsub("^RT\\s?(\\s:\\s)?", "", y)
        y <- gsub(";\\s|:\\s|\\s-+\\s", "\\. ", y)
        y <- gsub("[^a-zA-Z0-9\\.\\?!'-]", " ", y)
        y <- gsub("\\s*!+", ". ", y)
        y <- gsub("\\s*\\?+", ". ", y)
        y <- gsub("\\.{2,}", ". ", y)
        y <- gsub("-+", "-", y)
        y <- gsub("(\\s+\\.\\s+)", ". ", y)
        y <- gsub("(\\.\\s\\.)|(-\\s-)|(\\s+$)|(^\\s+)|(^\\.\\s)|(\\s'\\s)", "", y)
        y <- gsub("\\s+", " ", y)
        return(y)
}
.clean <- cmpfun(.clean)
# clean(c("I'll be there for you; I'd live and I'd die for you. I am Sam. Sam I am.", "Yes, I am.  "))
